server:
  port: 8765

spring:
  application:
    name: zuul-server
  sleuth:
    sampler:
      probability: 1.0
  zipkin: 
    baseUrl: ${ZIPKIN_SERVER:http://localhost:9411/}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

eureka: 
  client: 
    serviceUrl: 
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance: 
    preferIpAddress: true
    hostname: localhost